# Generated by Django 5.2.8 on 2025-11-17 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='server.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название свойства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('property_type', models.CharField(choices=[('number', 'Число'), ('boolean', 'Булево значение'), ('text', 'Текст')], max_length=10, verbose_name='Тип свойства')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='Числовое значение')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Булево значение')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текстовое значение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='server.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
                'ordering': ['-created_at'],
            },
        ),
    ]
